import {
  comp,
  generateComponents,
  type ProviderDefinition,
} from '@blastdom/components-generator';

const definition: ProviderDefinition = {
  name: 'bdom.mui.material',
  description: '',
  version: '0.1.0',
  author: 'Aurimas Niekis <aurimas@niekis.lt>',
  url: 'https://github.com/blastdom/components-mui-material',
  source: 'framjet',
  options: {
    importsPrefix: '@mui/material/',
    componentNamePrefix: 'mui.m.',
  },
  components: [
    comp('Accordion'),
    comp('AccordionActions'),
    comp('AccordionDetails'),
    comp('AccordionSummary'),
    comp('Alert'),
    comp('AlertTitle'),
    comp('AppBar'),
    comp('Autocomplete'),
    comp('Avatar'),
    comp('AvatarGroup'),
    comp('Backdrop'),
    comp('Badge'),
    comp('BottomNavigation'),
    comp('BottomNavigationAction'),
    comp('Box'),
    comp('Breadcrumbs'),
    comp('Button'),
    comp('ButtonBase'),
    comp('ButtonGroup'),
    comp('Card'),
    comp('CardActionArea'),
    comp('CardActions'),
    comp('CardContent'),
    comp('CardHeader'),
    comp('CardMedia'),
    comp('Checkbox'),
    comp('Chip'),
    comp('CircularProgress'),
    comp('Collapse'),
    comp('Container'),
    comp('CssBaseline'),
    comp('Dialog'),
    comp('DialogActions'),
    comp('DialogContent'),
    comp('DialogContentText'),
    comp('DialogTitle'),
    comp('Divider'),
    comp('Drawer'),
    comp('Fab'),
    comp('Fade'),
    comp('FilledInput'),
    comp('FormControl'),
    comp('FormControlLabel'),
    comp('FormGroup'),
    comp('FormHelperText'),
    comp('FormLabel'),
    comp('GlobalStyles'),
    comp('Grid'),
    comp('Grow'),
    comp('Hidden'),
    comp('Icon'),
    comp('IconButton'),
    comp('ImageList'),
    comp('ImageListItem'),
    comp('ImageListItemBar'),
    comp('Input'),
    comp('InputAdornment'),
    comp('InputBase'),
    comp('InputLabel'),
    comp('LinearProgress'),
    comp('Link'),
    comp('List'),
    comp('ListItem'),
    comp('ListItemAvatar'),
    comp('ListItemButton'),
    comp('ListItemIcon'),
    comp('ListItemSecondaryAction'),
    comp('ListItemText'),
    comp('ListSubheader'),
    comp('Menu'),
    comp('MenuItem'),
    comp('MenuList'),
    comp('MobileStepper'),
    comp('Modal'),
    comp('NativeSelect'),
    comp('OutlinedInput'),
    comp('Pagination'),
    comp('PaginationItem'),
    comp('Paper'),
    comp('Popover'),
    comp('Popper'),
    comp('Radio'),
    comp('RadioGroup'),
    comp('Rating'),
    comp('ScopedCssBaseline'),
    comp('Select'),
    comp('Skeleton'),
    comp('Slide'),
    comp('Slider'),
    comp('Snackbar'),
    comp('SnackbarContent'),
    comp('SpeedDial'),
    comp('SpeedDialAction'),
    comp('SpeedDialIcon'),
    comp('Stack'),
    comp('Step'),
    comp('StepButton'),
    comp('StepConnector'),
    comp('StepContent'),
    comp('StepIcon'),
    comp('StepLabel'),
    comp('Stepper'),
    comp('SvgIcon'),
    comp('SwipeableDrawer'),
    comp('Switch'),
    comp('Tab'),
    comp('Table'),
    comp('TableBody'),
    comp('TableCell'),
    comp('TableContainer'),
    comp('TableFooter'),
    comp('TableHead'),
    comp('TablePagination'),
    comp('TableRow'),
    comp('TableSortLabel'),
    comp('Tabs'),
    comp('TabScrollButton'),
    comp('TextField'),
    comp({ name: 'ThemeProvider', importPath: '@mui/material/styles/ThemeProvider' }),
    comp('ToggleButton'),
    comp('ToggleButtonGroup'),
    comp('Toolbar'),
    comp('Tooltip'),
    comp('Typography'),
    comp('Zoom'),
  ],
};

generateComponents(definition);
